<?php

/**
 * @var $block \Tamara\Checkout\Block\PopulateTamara
 */
?>
<script>
    window.populateTamara = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getTamaraConfig()); ?>;
</script>
<script charset="utf-8" src="https://cdn.tamara.co/widget/product-widget.min.js"></script>
<?php
$lang = 'en';
if ($block->isArabicLanguage()) {
    $lang = 'ar';
}
?>
<script>
    require([
        'jquery'
    ], function($){
        var existTamaraPayment = setInterval(function() {
            if ($('.tamara-product-widget').length) {
                if (window.TamaraProductWidget) {
                    window.TamaraProductWidget.init({ lang: '<?= $lang; ?>' });
                    window.TamaraProductWidget.render();
                }
                clearInterval(existTamaraPayment);
            }
        }, 300);
    });
</script>