<?php

/**
 * @var $block \Tamara\Checkout\Block\PopulateTamara
 */

$widgetVersion = $block->getWidgetVersion();
$isProductionEnvironment = $block->isProductionEnvironment();
?>
<script>
    window.populateTamara = <?php /* @escapeNotVerified */ echo \json_encode($block->getTamaraConfig()); ?>;
</script>
<?php if ($widgetVersion == 'v1') : ?>
    <?php if ($isProductionEnvironment): ?>
        <script charset="utf-8" defer src="https://cdn.tamara.co/widget/installment-plan.min.js"></script>
    <?php else: ?>
        <script charset="utf-8" defer src="https://cdn-sandbox.tamara.co/widget/installment-plan.min.js"></script>
    <?php endif; ?>
<?php else: ?>
    <?php if ($widgetVersion == 'v2') : ?>
        <?php if ($isProductionEnvironment): ?>
            <script charset="utf-8" defer src="https://cdn.tamara.co/widget-v2/tamara-widget.js"></script>
        <?php else: ?>
            <script charset="utf-8" defer src="https://cdn-sandbox.tamara.co/widget-v2/tamara-widget.js"></script>
        <?php endif; ?>
    <?php else: ?>
        <?php if ($isProductionEnvironment): ?>
            <script charset="utf-8" defer src="https://cdn.tamara.co/widget-v2/tamara-widget.js"></script>
            <script charset="utf-8" defer src="https://cdn.tamara.co/widget/installment-plan.min.js"></script>
        <?php else: ?>
            <script charset="utf-8" defer src="https://cdn-sandbox.tamara.co/widget-v2/tamara-widget.js"></script>
            <script charset="utf-8" defer src="https://cdn-sandbox.tamara.co/widget/installment-plan.min.js"></script>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>

