<?php
/**
 * @var $block \Tamara\Checkout\Block\Product\Popup
 */
if (!$block->availableToShow()) {
    goto end;
}
$productFinalPrice = $block->getCurrentProductPrice();
$availableMethod = $block->getPaymentMethodForPdpWidget($productFinalPrice);
?>

<?php if (!empty($availableMethod)): ?>
    <?php
    $lang = 'en';
    if ($block->isArabicLanguage()) {
        $lang = 'ar';
    }
    ?>
    <script charset="utf-8" src="https://cdn.tamara.co/widget/product-widget.min.js"></script>
    <script>
        require(['jquery', 'jquery/ui'], function($){
            var countExistTamaraProductWidget = 0;
            var existTamaraProductWidget = setInterval(function() {
                if ($('#tamara-product-widget').length && window.TamaraProductWidget) {
                    $("#tamara-product-widget").empty();
                    window.TamaraProductWidget.init({ lang: '<?= $lang; ?>' });
                    window.TamaraProductWidget.render();
                    clearInterval(existTamaraProductWidget);
                }
                if (++countExistTamaraProductWidget > 33) {
                    clearInterval(existTamaraProductWidget);
                }
            }, 300);
        });
    </script>

    <?php if ($availableMethod['name'] == \Tamara\Checkout\Gateway\Config\PayLaterConfig::PAYMENT_TYPE_CODE): ?>
        <div class="tamara-product-widget" id="tamara-product-widget" data-payment-type="paylater" data-disable-product-limit="true" data-disable-paylater="false" data-pay-later-max-amount="<?= $availableMethod['max_limit'] ?>" data-price="<?= $productFinalPrice; ?>" data-currency="<?= $block->getStoreCurrencyCode(); ?>" data-disable-installment="true"  data-lang="<?= $lang; ?>"></div>
    <?php else: ?>
        <?php
            $numberOfInstallments = \Tamara\Checkout\Gateway\Config\InstalmentConfig::getInstallmentsNumberByPaymentCode($availableMethod['name']);
        ?>
        <div class="tamara-product-widget" id="tamara-product-widget" data-disable-paylater="true" data-price="<?= $productFinalPrice; ?>" data-currency="<?= $block->getStoreCurrencyCode(); ?>" data-payment-type="installment" data-lang="<?= $lang; ?>" data-number-of-installments="<?= $numberOfInstallments; ?>" data-installment-minimum-amount="<?= $availableMethod['min_limit']; ?>"></div>
    <?php endif; ?>
<?php endif; ?>
<?php
    end:
?>