<?php
/**
 * @var $block Tamara\Checkout\Block\Success
 */
?>

<div class="tamara-success-title">
    <h2><?php echo __('Thank you!') ?></h2>
</div>
<?php $orderId = $block->getData('order_id'); ?>
<div id="success-area" data-bind="scope: 'tamara-success'">
    <input id="order_id" type="hidden" value="<?php echo $orderId; ?>">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<?php
$scriptString = 'window.successTamara = ';
$scriptString .= \json_encode($block->getTamaraConfig());
$scriptString2 = '
{
    "#success-area": {
        "Magento_Ui/js/core/app": {
            "components": {
                "tamara-success": {
                    "component": "Tamara_Checkout/js/view/success",
                    "template" : "Tamara_Checkout/success"
                }
            }
        }
    }
}
';
?>
<?php if (class_exists('\Magento\Framework\View\Helper\SecureHtmlRenderer')): ?>
    <?php /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */ ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', ['type' => 'text/x-magento-init'], $scriptString2, false) ?>
<?php else: ?>
    <script>
        <?php echo $scriptString ?>
    </script>
    <script type="text/x-magento-init">
        <?php echo $scriptString2 ?>
    </script>
<?php endif; ?>
